apiVersion: v1
kind: Service
metadata:
  name: bluegreen-blue-svc
  namespace: bluegreen
  labels:
    app: bluegreen
    version: blue-v1
spec:
  type: ClusterIP
  selector:
    app: bluegreen
    version: blue-v1
  ports:
    - name: http
      port: 80
      targetPort: 80
